name: Cubey
version: '${project.version}'
main: cubey.cubey.Cubey
api-version: 1.19
depend:
  - kotlin-stdlib

commands:
  cubey:
    description: cubey command
    usage: /<command>
    aliases: [cube, cu, c]
